name: energy_pipeline
version: "1.0.0"
config-version: 2

profile: energy_pipeline

model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  energy_pipeline:
    staging:
      +materialized: view
      +schema: silver

      billing:
        +materialized: view

      complaints:
        +materialized: view

      tariffs:
        +materialized: view

      grid:
        +materialized: view

    marts:
      +materialized: table
      +schema: gold

      customers:
        +materialized: table

      finance:
        +materialized: table

      operations:
        +materialized: table
